version: '3.7'

services:
  hathermos:
    build: .
    image: wiibleyde/hathermos:latest
    container_name: hathermos
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # database.db, ports.json, logs.log, serversConfig.json are stored in /srv/hathermos_data but in the container they are stored in /app
      - /srv/hathermos_data:/app/data
    networks:
      - net

networks:
  net:
    driver: bridge
